opengisch/libqfieldsync

layer.py, offline_converter.py, utils/xml.py
This new function is used in the new qfieldsync "convert to cloud project" feature (more bits coming in on the qfieldsync repository).
The function takes a source layer and writes a geopackage equivalent in the provided destination directory. If the source layer is a geopackage, the function merely copies the dataset.
If the source layer isn't a geopackage, it'll make a copy of the original dataset while being careful to respect pre-existing subset string filter, and insuring that joined fields as well as virtual fields remain as such (i.e. aren't made permanent).
=> Add a convert_to_gpkg function to the layer source object

offline_converter.py
Also add an option to disable the basemap creation by passing `create_basemap=True`.
=> Don't break packaging the project when the configured base layer no longer exists

layer.py
This fixes a serious bug with the qfieldsync plugin when run against QGIS 3.16 windows (using the old installer). It was discovered during the QField workshop @ FOSS4G by participant  Aaron Laver.
Long story short here, there's a problem with the old installer (and/or 3.16 itself) whereas the python API for the QgsVectorFileWriter.writeAsVectorFormatV2 function doesn't return the tuple as stated in the API documentation. The fix here is harmless. It's good practice to use the returned value, but if it ain't there, we can use the destination filepath we pass on as parameter.
With this fix in, I can successfully convert project to QFieldCloud using 3.16 LTR on windows :partying_face:
=> Fix cloud project converter against QGIS 3.16 windows (old installer)

offline_converter.py, project.py
The code remained there for quite some time, but it seems it is no longer needed, there is no UI and is threat for potential errors. As far as I know, @gacarrillor used the code in the past but this is no longer the case. Are you ok to remove it?
=> Remove support for offline_copy_only_selected_features configuration

offline_converter.py
=> If you save a project without QGIS GUI, the project no longer has `theMapCanvas` canvas

project_checker.py
Fix https://github.com/opengisch/qfieldsync/issues/414
=> Remove unnecessary string .format that also breaks on raster layers

offline_converter.py
- Fix https://github.com/opengisch/qfieldsync/issues/417 and https://github.com/opengisch/qfieldsync/issues/411 .
- Fix a QFieldSync respecting PostGIS layers configured as "direct access" not being packaged, as reported from @3nids
- Clean up code responsible for unsupported QGIS versions <3.16
=> Fix post-processing layers by ensuring the availability of remoteLayerId

project_checker.py
This warning is triggered by filenames containing special characters. E.g. `Übersichtskarte.gpkg`. The filename containing the special character is not presented to the user so far (only the layername, that is not a problem by itself). By showing that also, the error is easier to interpret.
=> Add affected filename to warning

layer.py
In short, the `photo_naming` was renamed to `attachment_naming` and it broke
projects configured with older version as reported in [#487](https://github.com/opengisch/qfieldsync/issues/487) .
=> Added compatibility with QFieldSync <4.3 and QField <2.7

offline_converter.py
Fixes https://github.com/opengisch/QField/issues/4697
=> Fix exporting of geometry-less vector layers when offlining using area of interest

libqfieldsync/layer.py
This PR adds a new layer source property to handle expression driven locking of geometry at the individual feature level.
=> Add a locked geometry expression string setting

libqfieldsync/project_checker.py
=> Avoid warning people that a read-only layer will be read-only on the cloud

libqfieldsync/offline_converter.py
ATM, packaging a project for QField USB cable export crashes if [x] only copy features in area of interest is checked and the bounding box can't be transformed to a given layer CRS.
Instead, let's handle that scenario graciously and warn the user.
=> Deal with failure to reproject area of interest bounding box

libqfieldsync/offline_converter.py
`Qgis.GeometryType` was introduced only in 3.30. See: https://api.qgis.org/api/3.30/classQgis.html#a84964253bb44012b246c20790799c04d 
Fix https://github.com/opengisch/qfieldsync/issues/552
=> Make QFieldSync work with older QGIS versions prior to 3.30

libqfieldsync/utils/bad_layer_handler.py, libqfieldsync/utils/qgis.py
Note there is a commented implementation of it that causes QGIS to crash with core dump. While the proposed implementation is more correct, the pragmatic move is just to set the `QgsProjectBadLayerHandler` globally.
=> Add a context manager setting a custom `QgsProjectBadLayerHandler`

libqfieldsync/offliners.py
If the selection by BBOX did not select anything, make sure we fool `QgsOfflineEditing` something is selected. Otherwise when `layer.selectedFeatureIds().isEmpty()`, `QgsOfflineEditing` dumps all features. NOTE that `layer.selectedFeatureIds()` should be renamed to `layer.requestedFeaturesIds()`, as it does not indicate actual features ids being already selected.
This was wrongly applied on non-spatial layers, which caused them to be exported as empty layers.
Fix https://github.com/opengisch/qfieldcloud/issues/874
=> Fix geometry-less exported as empty layers

libqfieldsync/offline_converter.py
This pull request dramatically (maybe I'm being a bit too... dramatic :wink: ) increase packaging speed in large projects (or projects containing slow remote data sources) by avoiding the cost of a full project load when merely wanting to fetch the map canvas XML.
In addition, a new convert() function parameter allows skipping of a final project reload when not needed (i.e., when packaging projects on the cloud).
=> Convert/package faster!

libqfieldsync/offline_converter.py
A regression slipped into 4.8.0 with regards to basemap creation during cable export.
Long story short, the UI is a bit deceptive and makes it look like the area of interest is only tied to filtering of feature when in fact it's also tied to basemap creation.
The updated logic in this PR fixes the regression, and seems to be easier to read too.
=> Fix regression with basemap creation, which also uses area of interest

libqfieldsync/layer.py
This PR adds a bunch of tracking-related properties to our Layer class, aimed at dictating tracking session within a given project through qfieldsync.
=> Add layer tracking session properties

libqfieldsync/offliners.py
This fixes a serious issue with QGIS core offliner whereas vector layers with a CRS not matching that of the project CRS can have all features gone missing when packaging cloud projects. 
Fixes https://github.com/opengisch/QField/issues/5094
=> When filtering features by bounding box, insure bounding box CRS matches that of the layer

libqfieldsync/offline_converter.py
Force delete the `QgsProject`, otherwise the `QgsApplication` might be deleted by the time the project is garbage collected
=> Prevent crashes when the `QgsApplication` is deleted in headless mode

.github/workflows/continuous_integration.yml
Since QGIS images moved to .deb installed QGIS, some stuff have changed and the CI is no longer working properly.
Therefore I have changed the CI not to use `latest`, but the last QGIS image using the old setup.
While this will work for the next few weeks/months, this needs proper fix in the near future.
@dddpt one for you whenever you have time to fix this.
=> Temporarily fix the tests with the workaround of using old QGIS images

libqfieldsync/layer.py
QGIS4 and some parts of the code (e.g. packagers) already depend on own `QgsProject` instances. However, the `LayerSource` assumed it always works with the global instance, which is not always the case.
=> Support other than global `QgsProject` instance in the `LayerSource`

libqfieldsync/layer.py, libqfieldsync/project_checker.py
Sometimes online WMS layers are not accessible because of multiple reasons:
- temporary network/server error
- firewall
- network access
- etc
Just ignore these layers on the server side and don't remove them.
=> Do not remove broken WMS layers during packaging

libqfieldsync/layer.py
New layer property allowing for users to configure the value map editor widget's toggle buttons interface.
See https://github.com/opengisch/qfieldsync/pull/584 on the qfieldsync side of things.
=> Add a value map button interface threshold layer setting

libqfieldsync/layer.py
This PR fixes https://github.com/opengisch/QField/issues/5451 .
Background: until now, libqfieldsync had a limited self-curated detection/handling of sidecar files. The PR retires that code in favor of QGIS' `QgsFileUtils.sidecarFilesForPath(path)` , which does a much better job at returning sidecar files and is future proof (as it relies on individual providers to return sidecar lists, see https://github.com/qgis/QGIS/blob/master/src/core/qgsfileutils.cpp#L457-L475).
Practically speaking, not capturing all sidecar files meant that projects both packaged for USB cable transfer _as well as_ cloud projects could have key files missing and break layers (see above-mentioned issue).
=> Use QGIS' utility function to detect and copy sidecar files

libqfieldsync/project.py
This is the libqfieldsync counterpart to https://github.com/opengisch/qfieldsync/pull/601 .
@suricactus , keen to have your review on this one.
=> Add a project settting to keep track of map themes' default active layer

.github/workflows/continuous_integration.yml, libqfieldsync/layer.py, tests/test_layer.py
PR fixes https://github.com/opengisch/qfieldsync/issues/604 
(Regression introduced in https://github.com/opengisch/libqfieldsync/commit/ad68b323ac79d45f2f82a7501fce3e4bdc355e89)
=> Fix project cloud convert code

libqfieldsync/offline_converter.py, libqfieldsync/offliners.py, libqfieldsync/utils/qgis.py, tests/test_offline_converter_minioffliner.py, tests/test_offline_converter_qgiscore.py
This is complement for the [PR](https://github.com/opengisch/qfieldsync/pull/615) on QFieldSync
=> Adding the functionality for specify packaged project filename and title

libqfieldsync/offline_converter.py
Removing Layer groups removed when no layers left in them
Test project:
[crop_monitoring_000.zip](https://github.com/user-attachments/files/17775665/crop_monitoring_000.zip)
Implemented on QFieldSync plugin on the PR https://github.com/opengisch/qfieldsync/pull/623
Fix https://github.com/opengisch/qfieldsync/issues/587
=> Removing Layer groups removed when no layers left in them

libqfieldsync/offline_converter.py
This fixes the warning of deprecation of the `setAutoTransaction`
Reported on https://github.com/opengisch/qfieldsync/issues/612
=> Fixing deprecation of setAutoTransaction to setTransactionMode

libqfieldsync/project_checker.py
The `QgsMapLayer.source()` does not return a pure path, that's why we
should always use `layer_source.filename`.
Fixes https://github.com/opengisch/qfieldsync/issues/630#issuecomment-2525183402
The bug was introduced in https://github.com/opengisch/libqfieldsync/pull/96
@m-kuhn can you please review if I overlooked something else?
=> Fix checking for external layers relative to the project file

.github/workflows/continuous_integration.yml, libqfieldsync/offliners.py
In GDAL 3.10.0 the return value of `ogr.CreateDataSource` changed from `ogr.DataSource` to `gdal.Dataset`.
Experienced by Windows users using OSGeo4W: https://github.com/jef-n/OSGeo4W/commit/5469ac4aadc47cab8f535395e6e92c56324d72ef
And announced here: https://github.com/OSGeo/gdal/blob/v3.10.0/NEWS.md
Fixes https://github.com/opengisch/qfieldsync/issues/633
=> Fix typing for GDAL 3.10.0+

.pre-commit-config.yaml, libqfieldsync/offline_converter.py, libqfieldsync/offliners.py, libqfieldsync/project_checker.py
This PR adds `isort` to pre-commit hooks configuration.
As well as reformat existing code using isort.
=> Add isort pre commit hook

libqfieldsync/offline_converter.py, libqfieldsync/project.py
This PR makes the cable export generate a `mbtiles` basemap for QField, thus enabling multiple raster zoom levels.
Subtasks:
see https://github.com/opengisch/qfieldsync/pull/637
=> Export basemap as mbtiles during cable export

libqfieldsync/offline_converter.py
This PR makes several consecutive offline packaging to the same folder possible.
Before, the offline packager was throwing an error if the target basemap destination file was already existing, due to the underlying `native:tilesxyzmbtiles` processing algorithm. Which is not the case anymore.
=> Make basemap export not fail anymore when package already exists

libqfieldsync/layer.py
Actually this is not working fine in QFieldSync now, because the `bad_layer_handler` is not set, due to crashes of QGIS.
At least we prevent a warning that the layer will not be packaged, while it will be in the cloud environment.
=> Only show warning if the localized dataset is not present

libqfieldsync/layer.py
Until now, our [x] lock geometry toggle was locking quite a lot. It was locking:
- feature addition
- feature deletion
- geometry modification
Users have requested a finer grained set of locks. This PR implements that by adding 4 distinct locked states:
- feature addition
- feature deletion
- geometry modification
- attribute editing (a nice 4th lock here that was not possible before)
Each of these locks come with a data-defined property that allows for the locks to be turned on/off based on expressions evaluated against a given feature and/or various scopes.
=> Explode geometry locked into 4 distinct locked states

libqfieldsync/offline_converter.py, libqfieldsync/project.py, tests/data/geometryless_project/project.qgs, tests/data/pk_project/project.qgs
This PR intends to use the project's basemap tile size as a parameter when calling the underlying QGIS processing algorithm used to generate mbtiles.
=> clean(basemap): use project's tile size when generating basemap

libqfieldsync/layer.py
When configuring QFieldCloud packaging options, we might get the confusing scenario of configuring a file based vector layer (gpkg) with "Directly access datasource" which will make the layer editable on QField, but never synchronizable back to QFieldCloud. This is bad and may cause potential data loss.
So we can just disable this option in a way, that "Directly access datasource" is available for :
1) non-file based layers (virtual, postgis, wfs etc)
2) file based layers that are in read-only mode (readonly gpkg)
In this PR I also enabled removing localized and virtual layers from the project.
=> fix: do not allow "Directly access datasource" on QFieldCloud packaging actions for file based layers that are not readonly

libqfieldsync/offline_converter.py
NOTE: while it will be much more readable to pass `export_type` parameter to have a default value of `ExportType.Cable`, we cannot reference an Enum as a default value in a QGIS plugin, as when the file reloaded (e.g. enable/disable the plugin, Plugin reloader), the enum will have a different address and comparisons will fail.
=> fix: do not use Enum as default value which causes the plugin to fail after reloading

libqfieldsync/project.py
Uses constant strings for initial map modes instead of free-form strings. This prevents errors and typos in the configuration. It also adds a fallback to "browse" if the value is invalid.
=> Uses constant strings for map modes
