offline_converter.py

There were a series of mistakes lately, caused by the overcluttering the `convert` method. Even the linter was saying it was overly complex. At least huge block of code are now named, but there is the potential for even more.
- moved the basemap requirements check to standalone function
- don't break on failed basemap generation
- use the convention "o_" for "original"/online and "e_" for "exported"/offline
- move layer postprocessing to standalone function
- drop support for QGIS <3.16.1

Demystify the convert method

---

offline_converter.py
utils/qgis.py

Added support for python 3.5

---

layer.py
offline_converter.py

@nirvn I moved all these checks from around the codebase to a single place in the layer source.

Metadata and filename path checks are now in LayerSource

---

offline_converter.py
utils/file_utils.py

Fix https://github.com/opengisch/qfieldsync/issues/302

Check if the filename is using only ASCII chars and the file encoding is UTF8

---

offline_converter.py

Miserabely failed with https://github.com/opengisch/libqfieldsync/pull/9
fix https://github.com/opengisch/qfieldsync/issues/307

Fix typing yet again

---

layer.py

Doc: https://docs.python.org/3/library/pathlib.html#methods second paragraph

Don't throw an exception on python prior to 3.8

---

layer.py

Should fix https://github.com/opengisch/qfieldcloud/discussions/81

Add support for file-based vector tile layer sources

---

offline_converter.py

Restore map theme support

---

project_checker.py

Before it was a bit too noisy before uploading to the cloud or packaging.

Make lack of configured action less annoying

---

.pre-commit-config.yaml
offline_converter.py
utils/qgis.py

Bump pre-commit black version

---

project.py

Title says it all.
The libqfieldsync side of https://github.com/opengisch/QField/pull/2740

Add a maximum image attachment width/height property

---

layer.py

See https://github.com/opengisch/QField/pull/3520 and https://github.com/opengisch/qfieldsync/pull/474 for more details on functionality and implementation.

Add the relationship_maximum_visible property to LayerSource

---

.pre-commit-config.yaml
layer.py

See https://github.com/opengisch/QField/pull/3851 on the QField side and the recent work done in QGIS itself such as https://github.com/qgis/QGIS/pull/51594.

Move away from photo-centric external resource support into file,image,audio,video

---

offline_converter.py
tests/test_offline_converter.py

Might solve intances of `assert self.area_of_interest_crs.isValid()`

Allow specifying CRS instead of authid

---

layer.py

Fixes https://github.com/opengisch/qfieldsync/issues/514

Make virtual vector layers to support direct access only

---

layer.py
offline_converter.py
utils/qgis.py

Check the commit messages for more info.

Fix localized paths support in libqfieldsync for the cloud

---

libqfieldsync/layer.py

Improve layer.is_localized_path() logic

---

libqfieldsync/offline_converter.py

Complements #68 with some docs.

Added a bit of explanations what and why we use a temporary project

---

libqfieldsync/project.py

Needed for a UI/UX in qfieldsync plugin; relevant PR in qfieldsync repository to be opened soon.

Add a pair of project configuration properties to handle auto push settings

---

libqfieldsync/offline_converter.py

Needed to fix https://github.com/opengisch/qfieldsync/issues/564

Handle empty area of interest WKT string to fix project cable packaging

---

tests/data/localized_project/geometryless.csv
tests/data/localized_project/project.qgs
tests/test_offline_converter_minioffliner.py
tests/test_offline_converter_qgiscore.py

Ideally we'd also test it on the QFieldCloud side of things, but this is already better than zero coverage.

Add test coverage for localized paths

---

libqfieldsync/project.py

A couple of project-level settings needed to implement geofencing in qfieldsync / QField.

Add project geofencing settings

---

libqfieldsync/offline_converter.py

Fix https://github.com/opengisch/qfieldsync/issues/594

Fix "No basemap layer selected" error when map theme is used for basemap

---

libqfieldsync/project_checker.py
libqfieldsync/utils/file_utils.py

This is the replacement of the [PR](https://github.com/opengisch/qfieldsync/pull/614#pullrequestreview-2386030508)

Adding validator for files and path

---

libqfieldsync/project_checker.py

Adding Warning for layers outside the current project home directory

Adding Warning for layers outside the current project home directory

---

.github/workflows/continuous_integration.yml

Qgis 3.16 is eol for a long time
Ubuntu 20.04 will be retired soon as action runners

Remove old infra tests

---

libqfieldsync/project_checker.py

The last message in the screenshot:

Adding warning if offline layers is not a supported format for cloud
